/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as WatchersRouteImport } from "./routes/watchers"
import { Route as SettingsRouteImport } from "./routes/settings"
import { Route as RulesRouteImport } from "./routes/rules"
import { Route as FolderPresetRouteImport } from "./routes/folder-preset"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as WatchersIndexRouteImport } from "./routes/watchers/index"
import { Route as SettingsIndexRouteImport } from "./routes/settings/index"
import { Route as FolderPresetsIndexRouteImport } from "./routes/folder-presets/index"
import { Route as AiWatchersIndexRouteImport } from "./routes/ai-watchers/index"
import { Route as WatchersWatcherIdIndexRouteImport } from "./routes/watchers/$watcherId/index"
import { Route as SettingsUpdateIndexRouteImport } from "./routes/settings/update/index"
import { Route as SettingsOpenaiIndexRouteImport } from "./routes/settings/openai/index"
import { Route as RulesRuleIdIndexRouteImport } from "./routes/rules/$ruleId/index"
import { Route as FolderPresetsFolderPresetIdIndexRouteImport } from "./routes/folder-presets/$folderPresetId/index"
import { Route as CategoryCategoryIdIndexRouteImport } from "./routes/category/$categoryId/index"
import { Route as AiWatchersAiwatcherIdIndexRouteImport } from "./routes/ai-watchers/$aiwatcherId/index"

const WatchersRoute = WatchersRouteImport.update({
  id: "/watchers",
  path: "/watchers",
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: "/rules",
  path: "/rules",
  getParentRoute: () => rootRouteImport,
} as any)
const FolderPresetRoute = FolderPresetRouteImport.update({
  id: "/folder-preset",
  path: "/folder-preset",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const WatchersIndexRoute = WatchersIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => WatchersRoute,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => SettingsRoute,
} as any)
const FolderPresetsIndexRoute = FolderPresetsIndexRouteImport.update({
  id: "/folder-presets/",
  path: "/folder-presets/",
  getParentRoute: () => rootRouteImport,
} as any)
const AiWatchersIndexRoute = AiWatchersIndexRouteImport.update({
  id: "/ai-watchers/",
  path: "/ai-watchers/",
  getParentRoute: () => rootRouteImport,
} as any)
const WatchersWatcherIdIndexRoute = WatchersWatcherIdIndexRouteImport.update({
  id: "/$watcherId/",
  path: "/$watcherId/",
  getParentRoute: () => WatchersRoute,
} as any)
const SettingsUpdateIndexRoute = SettingsUpdateIndexRouteImport.update({
  id: "/update/",
  path: "/update/",
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsOpenaiIndexRoute = SettingsOpenaiIndexRouteImport.update({
  id: "/openai/",
  path: "/openai/",
  getParentRoute: () => SettingsRoute,
} as any)
const RulesRuleIdIndexRoute = RulesRuleIdIndexRouteImport.update({
  id: "/$ruleId/",
  path: "/$ruleId/",
  getParentRoute: () => RulesRoute,
} as any)
const FolderPresetsFolderPresetIdIndexRoute =
  FolderPresetsFolderPresetIdIndexRouteImport.update({
    id: "/folder-presets/$folderPresetId/",
    path: "/folder-presets/$folderPresetId/",
    getParentRoute: () => rootRouteImport,
  } as any)
const CategoryCategoryIdIndexRoute = CategoryCategoryIdIndexRouteImport.update({
  id: "/category/$categoryId/",
  path: "/category/$categoryId/",
  getParentRoute: () => rootRouteImport,
} as any)
const AiWatchersAiwatcherIdIndexRoute =
  AiWatchersAiwatcherIdIndexRouteImport.update({
    id: "/ai-watchers/$aiwatcherId/",
    path: "/ai-watchers/$aiwatcherId/",
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/folder-preset": typeof FolderPresetRoute
  "/rules": typeof RulesRouteWithChildren
  "/settings": typeof SettingsRouteWithChildren
  "/watchers": typeof WatchersRouteWithChildren
  "/ai-watchers/": typeof AiWatchersIndexRoute
  "/folder-presets/": typeof FolderPresetsIndexRoute
  "/settings/": typeof SettingsIndexRoute
  "/watchers/": typeof WatchersIndexRoute
  "/ai-watchers/$aiwatcherId/": typeof AiWatchersAiwatcherIdIndexRoute
  "/category/$categoryId/": typeof CategoryCategoryIdIndexRoute
  "/folder-presets/$folderPresetId/": typeof FolderPresetsFolderPresetIdIndexRoute
  "/rules/$ruleId/": typeof RulesRuleIdIndexRoute
  "/settings/openai/": typeof SettingsOpenaiIndexRoute
  "/settings/update/": typeof SettingsUpdateIndexRoute
  "/watchers/$watcherId/": typeof WatchersWatcherIdIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/folder-preset": typeof FolderPresetRoute
  "/rules": typeof RulesRouteWithChildren
  "/ai-watchers": typeof AiWatchersIndexRoute
  "/folder-presets": typeof FolderPresetsIndexRoute
  "/settings": typeof SettingsIndexRoute
  "/watchers": typeof WatchersIndexRoute
  "/ai-watchers/$aiwatcherId": typeof AiWatchersAiwatcherIdIndexRoute
  "/category/$categoryId": typeof CategoryCategoryIdIndexRoute
  "/folder-presets/$folderPresetId": typeof FolderPresetsFolderPresetIdIndexRoute
  "/rules/$ruleId": typeof RulesRuleIdIndexRoute
  "/settings/openai": typeof SettingsOpenaiIndexRoute
  "/settings/update": typeof SettingsUpdateIndexRoute
  "/watchers/$watcherId": typeof WatchersWatcherIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/folder-preset": typeof FolderPresetRoute
  "/rules": typeof RulesRouteWithChildren
  "/settings": typeof SettingsRouteWithChildren
  "/watchers": typeof WatchersRouteWithChildren
  "/ai-watchers/": typeof AiWatchersIndexRoute
  "/folder-presets/": typeof FolderPresetsIndexRoute
  "/settings/": typeof SettingsIndexRoute
  "/watchers/": typeof WatchersIndexRoute
  "/ai-watchers/$aiwatcherId/": typeof AiWatchersAiwatcherIdIndexRoute
  "/category/$categoryId/": typeof CategoryCategoryIdIndexRoute
  "/folder-presets/$folderPresetId/": typeof FolderPresetsFolderPresetIdIndexRoute
  "/rules/$ruleId/": typeof RulesRuleIdIndexRoute
  "/settings/openai/": typeof SettingsOpenaiIndexRoute
  "/settings/update/": typeof SettingsUpdateIndexRoute
  "/watchers/$watcherId/": typeof WatchersWatcherIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/folder-preset"
    | "/rules"
    | "/settings"
    | "/watchers"
    | "/ai-watchers/"
    | "/folder-presets/"
    | "/settings/"
    | "/watchers/"
    | "/ai-watchers/$aiwatcherId/"
    | "/category/$categoryId/"
    | "/folder-presets/$folderPresetId/"
    | "/rules/$ruleId/"
    | "/settings/openai/"
    | "/settings/update/"
    | "/watchers/$watcherId/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/folder-preset"
    | "/rules"
    | "/ai-watchers"
    | "/folder-presets"
    | "/settings"
    | "/watchers"
    | "/ai-watchers/$aiwatcherId"
    | "/category/$categoryId"
    | "/folder-presets/$folderPresetId"
    | "/rules/$ruleId"
    | "/settings/openai"
    | "/settings/update"
    | "/watchers/$watcherId"
  id:
    | "__root__"
    | "/"
    | "/folder-preset"
    | "/rules"
    | "/settings"
    | "/watchers"
    | "/ai-watchers/"
    | "/folder-presets/"
    | "/settings/"
    | "/watchers/"
    | "/ai-watchers/$aiwatcherId/"
    | "/category/$categoryId/"
    | "/folder-presets/$folderPresetId/"
    | "/rules/$ruleId/"
    | "/settings/openai/"
    | "/settings/update/"
    | "/watchers/$watcherId/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FolderPresetRoute: typeof FolderPresetRoute
  RulesRoute: typeof RulesRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
  WatchersRoute: typeof WatchersRouteWithChildren
  AiWatchersIndexRoute: typeof AiWatchersIndexRoute
  FolderPresetsIndexRoute: typeof FolderPresetsIndexRoute
  AiWatchersAiwatcherIdIndexRoute: typeof AiWatchersAiwatcherIdIndexRoute
  CategoryCategoryIdIndexRoute: typeof CategoryCategoryIdIndexRoute
  FolderPresetsFolderPresetIdIndexRoute: typeof FolderPresetsFolderPresetIdIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/watchers": {
      id: "/watchers"
      path: "/watchers"
      fullPath: "/watchers"
      preLoaderRoute: typeof WatchersRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/settings": {
      id: "/settings"
      path: "/settings"
      fullPath: "/settings"
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/rules": {
      id: "/rules"
      path: "/rules"
      fullPath: "/rules"
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/folder-preset": {
      id: "/folder-preset"
      path: "/folder-preset"
      fullPath: "/folder-preset"
      preLoaderRoute: typeof FolderPresetRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/watchers/": {
      id: "/watchers/"
      path: "/"
      fullPath: "/watchers/"
      preLoaderRoute: typeof WatchersIndexRouteImport
      parentRoute: typeof WatchersRoute
    }
    "/settings/": {
      id: "/settings/"
      path: "/"
      fullPath: "/settings/"
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    "/folder-presets/": {
      id: "/folder-presets/"
      path: "/folder-presets"
      fullPath: "/folder-presets/"
      preLoaderRoute: typeof FolderPresetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/ai-watchers/": {
      id: "/ai-watchers/"
      path: "/ai-watchers"
      fullPath: "/ai-watchers/"
      preLoaderRoute: typeof AiWatchersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/watchers/$watcherId/": {
      id: "/watchers/$watcherId/"
      path: "/$watcherId"
      fullPath: "/watchers/$watcherId/"
      preLoaderRoute: typeof WatchersWatcherIdIndexRouteImport
      parentRoute: typeof WatchersRoute
    }
    "/settings/update/": {
      id: "/settings/update/"
      path: "/update"
      fullPath: "/settings/update/"
      preLoaderRoute: typeof SettingsUpdateIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    "/settings/openai/": {
      id: "/settings/openai/"
      path: "/openai"
      fullPath: "/settings/openai/"
      preLoaderRoute: typeof SettingsOpenaiIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    "/rules/$ruleId/": {
      id: "/rules/$ruleId/"
      path: "/$ruleId"
      fullPath: "/rules/$ruleId/"
      preLoaderRoute: typeof RulesRuleIdIndexRouteImport
      parentRoute: typeof RulesRoute
    }
    "/folder-presets/$folderPresetId/": {
      id: "/folder-presets/$folderPresetId/"
      path: "/folder-presets/$folderPresetId"
      fullPath: "/folder-presets/$folderPresetId/"
      preLoaderRoute: typeof FolderPresetsFolderPresetIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/category/$categoryId/": {
      id: "/category/$categoryId/"
      path: "/category/$categoryId"
      fullPath: "/category/$categoryId/"
      preLoaderRoute: typeof CategoryCategoryIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/ai-watchers/$aiwatcherId/": {
      id: "/ai-watchers/$aiwatcherId/"
      path: "/ai-watchers/$aiwatcherId"
      fullPath: "/ai-watchers/$aiwatcherId/"
      preLoaderRoute: typeof AiWatchersAiwatcherIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface RulesRouteChildren {
  RulesRuleIdIndexRoute: typeof RulesRuleIdIndexRoute
}

const RulesRouteChildren: RulesRouteChildren = {
  RulesRuleIdIndexRoute: RulesRuleIdIndexRoute,
}

const RulesRouteWithChildren = RulesRoute._addFileChildren(RulesRouteChildren)

interface SettingsRouteChildren {
  SettingsIndexRoute: typeof SettingsIndexRoute
  SettingsOpenaiIndexRoute: typeof SettingsOpenaiIndexRoute
  SettingsUpdateIndexRoute: typeof SettingsUpdateIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsIndexRoute: SettingsIndexRoute,
  SettingsOpenaiIndexRoute: SettingsOpenaiIndexRoute,
  SettingsUpdateIndexRoute: SettingsUpdateIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface WatchersRouteChildren {
  WatchersIndexRoute: typeof WatchersIndexRoute
  WatchersWatcherIdIndexRoute: typeof WatchersWatcherIdIndexRoute
}

const WatchersRouteChildren: WatchersRouteChildren = {
  WatchersIndexRoute: WatchersIndexRoute,
  WatchersWatcherIdIndexRoute: WatchersWatcherIdIndexRoute,
}

const WatchersRouteWithChildren = WatchersRoute._addFileChildren(
  WatchersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FolderPresetRoute: FolderPresetRoute,
  RulesRoute: RulesRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
  WatchersRoute: WatchersRouteWithChildren,
  AiWatchersIndexRoute: AiWatchersIndexRoute,
  FolderPresetsIndexRoute: FolderPresetsIndexRoute,
  AiWatchersAiwatcherIdIndexRoute: AiWatchersAiwatcherIdIndexRoute,
  CategoryCategoryIdIndexRoute: CategoryCategoryIdIndexRoute,
  FolderPresetsFolderPresetIdIndexRoute: FolderPresetsFolderPresetIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
